### ISSUE TITLE
Getting "Invalid magic bytes" with some files

### ISSUE THREAD

**Issue by Chochek** [LinusU/decode-ico#1]
For example with this `.ico` file: https://s3.amazonaws.com/www.invisionapp.com-studio/static/img/favicon.ico

```
Error: Invalid magic bytes
    at decodeIco (./node_modules/decode-ico/index.js:37:11)
    ...
```

**Comment by perry-mitchell** [comment]
Also with this icon: https://ex.bnbstatic.com/static/images/common/favicon.ico

**Comment by LinusU** [comment]
Sorry for never getting back on this, definitely want to take a look at this! PRs always welcome as well ☺️

**Comment by spencermountain** [comment]
thank you so much for this library @LinusU 
i've found one too, and am happy to help debug this issue.
https://q2r7c5n7.stackpathcdn.com/Warehouse/content/pics/favicon.ico
cheers

**Comment by spencermountain** [comment]
I put the buffer of the offending image into [sharp](https://github.com/lovell/sharp/) and it called it a png:
```
{ format: 'png',
  size: 1246,
  width: 32,
  height: 32,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 72,
  isProgressive: false,
  hasProfile: false,
  hasAlpha: true }
```
maybe it has different rules about magic bytes than this library does.

i'm afraid i'm a little out of my league at this point

**Comment by kchapelier** [comment]
The issue with those files is that they are not actual _ico_ files but _png_ files with an .ico extension. This works in browsers because they ignore both the extension and the mimeType sent by the server (the servers are indeed serving those as _image/x-icon_ in the provided examples) and instead read the file signature / magic bytes to decide how to decode those files. 

I'll try to submit a PR which handle those transparently, but whether this module should handle this is questionable. There are also probably _bmp_, _gif_ and even _jpg_ files masquerading as _ico_ files out there...

**Comment by LinusU** [comment]
For this use case, I would recommend [@canvas/image](https://github.com/node-gfx/image) instead which as of version 2.0.0 can handle ico files in addition to most other image formats. It looks at the magic bytes to decide how to decode the image, so should work regardless of file extension 🐎
